### ISSUE TITLE
SonarQube 4.3.3

### ISSUE THREAD

**Issue by xfreebird** [octo-technology/sonar-objective-c#63]
Hi,

It seems this plugin it will not compile for SonarQube 4.3.3 due to deprecated API.

Are there any plans to support the new API ?

**Comment by rompic** [comment]
@cyrilpicat any news?

**Comment by zippy1978** [comment]
Hi,

I saw that @xfreebird started the upgrade work and I decided to finish it.
I just issued a pull request on his fork, here: https://github.com/xfreebird/sonar-objective-c/pull/2

**Comment by cyrilpicat** [comment]
cool, that's great news Gilles!

If you want you can directly issue a pull request here.

cheers,

**Comment by rompic** [comment]
@xfreebird thanks a lot. this is great news!

**Comment by rompic** [comment]
5.0 is coming soon (Jan 2015). Do we have an overview of what has to be done to be ready for this update as well?

**Comment by xfreebird** [comment]
@zippy1978 you are a hero ! :)

**Comment by rompic** [comment]
concerning 5.0 only found: http://sonarqube.15.x6.nabble.com/sonar-dev-SonarQube-5-0-plugins-compatibility-td5028438.html

**Comment by zippy1978** [comment]
@cyrilpicat: pull request done (https://github.com/octo-technology/sonar-objective-c/pull/69) !

**Comment by aheritier** [comment]
sadly the 5.0 upgrade fails : https://gist.github.com/aheritier/6f0d9c4cd6aa7dcc4be0

**Comment by cyrilpicat** [comment]
thanks for the report. Can you open a new issue for this, please?

I had a look and it seems to be due to a deprecated API: http://jira.codehaus.org/browse/SONARPLUGINS-3810

Should be quite easy to fix.

**Comment by aheritier** [comment]
thx @cyrilpicat. Yes I will open a dedicated issue
