### ISSUE TITLE
oclint report created, files index in sonar, but vialotions don't show up?

### ISSUE THREAD

**Issue by rompic** [octo-technology/sonar-objective-c#71]
Hi i'm trying to set this up:

oc lint report:
<file name="/export/home/jenkins/workspace/project/ab/config/Config.m"><violation begincolumn="42" endcolumn="72" beginline="129" endline="129" priority="5" rule="unused method parameter">
The parameter '...' is unused.
</violation></file>

Sonar-Runner Log
10:14:35.873 DEBUG - Language of file 'config/Config.m' is detected to be 'objc'
10:14:36.288 INFO  - 598 files indexed
...

10:14:42.309 INFO  - Processing OCLint report /export/home/jenkins/workspace/project/ab/./sonar-reports/oclint.xml
10:14:42.310 DEBUG - Collection violations for /export/home/jenkins/workspace/project/ab/config/Config.m
10:14:42.311 DEBUG - File /export/home/jenkins/workspace/project/ab/config/Config.m was found in the project.

looks good. but the violations do not show up in sonar? any hints?

**Comment by Yao0729** [comment]
I have the same problem. 
Sonar: 5.0.1
Objective C plugin 0.4.0.

Does the Objective C fixing support Sonar 5.0.1?

**Comment by Yao0729** [comment]
It doesn't help....Here is my sonar-project.properties.

sonar.projectKey=Project
sonar.projectName=Project
sonar.projectVersion=1.0
sonar.language=objc

sonar.projectDescription=Description

sonar.sources=MyProject
sonar.tests=MyProjectTests

sonar.objectivec.project= MyProject.xcodeproj 

sonar.objectivec.appScheme=MyProject
sonar.objectivec.testScheme=MyProjectUnitTests

sonar.sourceEncoding=UTF-8

### sonar.junit.reportsPath=sonar-reports

### sonar.objectivec.coverage.reportPattern=sonar-reports/coverage*.xml

### sonar.objectivec.oclint.report=sonar-reports/oclint.xml

 sonar.objectivec.excludedPathsFromCoverage=._Tests._

oclint.xml is generated under sonar-reports/.

Here is the log that I get:
4:54:13.178 INFO  - Processing OCLint report /PATH/TO/sonar-reports/oclint.xml
14:54:13.180 DEBUG - Collection violations for blablablabla

I'm using
SonarQube v5.0.1
sonar-runner v2.4 (using brew)
oclint v0.8.1 (using brew)
Objective C plugin 0.4.0.

**Comment by rompic** [comment]
can you post a screenshot of your sonar quality Profiles page?

you could also try to start the sonar runner with the -X / --debug flag in the run-sonar.sh file to get additional information (and post this blabla in anonymized form):

`# SonarQube`
`echo -n 'Running SonarQube using SonarQube Runner'`
`runCommand /dev/stdout sonar-runner -X`

https://github.com/octo-technology/sonar-objective-c/issues/74

**Comment by Yao0729** [comment]
Sure. Thanks for your help.

Here is the screenshot of my profile page.
![screen shot 2015-03-22 at 9 00 58 pm](https://cloud.githubusercontent.com/assets/10376484/6774020/b0fb1a7e-d0d6-11e4-9c3e-f0c34e859756.png)

Here is the log
14:54:13.178 INFO  - Sensor org.sonar.plugins.objectivec.violations.OCLintSensor@529f5fdd...
14:54:13.178 INFO  - Processing OCLint report /PATH/TO/sonar-reports/oclint.xml
14:54:13.180 DEBUG - Collection violations for /PATH/TO/File
14:54:13.180 DEBUG - /PATH/TO/File was found in the project.
...
14:54:13.591 ERROR - Reporting 2332 violations.
14:54:13.678 INFO  - Sensor org.sonar.plugins.objectivec.violations.OCLintSensor@529f5fdd done: 500 ms
14:54:13.678 INFO  - Sensor InitialOpenIssuesSensor...
14:54:13.692 INFO  - Sensor InitialOpenIssuesSensor done: 14 ms
14:54:13.692 INFO  - Sensor ProjectLinksSensor...
14:54:13.699 INFO  - Sensor ProjectLinksSensor done: 7 ms
14:54:13.700 INFO  - Sensor VersionEventsSensor...
14:54:13.742 INFO  - Sensor VersionEventsSensor done: 42 ms
14:54:13.742 INFO  - Sensor FileHashSensor...
14:54:13.771 INFO  - Sensor FileHashSensor done: 29 ms
14:54:13.771 INFO  - Sensor SCM Sensor (wrapped)...
14:54:13.938 INFO  - Sensor SCM Sensor (wrapped) done: 167 ms
14:54:13.938 INFO  - Sensor CPD Sensor (wrapped)...
14:54:13.938 INFO  - DefaultCpdEngine is used for objc
14:54:13.960 INFO  - Cross-project analysis disabled
14:54:13.965 DEBUG - Populating index from [moduleKey=Project, relative=Project/File, abs=Path/To/File]
...
14:54:14.346 DEBUG - Detection of duplications for [moduleKey=Project, relative=Project/File, abs=Path/To/File]
...
14:54:14.596 INFO  - Sensor CPD Sensor (wrapped) done: 658 ms
14:54:14.889 INFO  - Execute decorators...
14:54:14.890 DEBUG - Decorators: ManualMeasureDecorator -> QProfileEventsDecorator -> org.sonar.batch.design.ProjectDsmDecorator@12ebdf8b -> org.sonar.batch.design.SubProjectDsmDecorator@3ba12861 -> org.sonar.batch.design.DirectoryDsmDecorator@516216dc -> FileTangleIndexDecorator -> SumDuplicationsDecorator -> org.sonar.plugins.core.issue.IssueTrackingDecorator@7ecaef41 -> UnitTestDecorator -> org.sonar.plugins.core.security.ApplyProjectRolesDecorator@1a099ee4 -> org.sonar.plugins.core.sensors.DirectoriesDecorator@59c4057d -> org.sonar.plugins.core.sensors.FilesDecorator@54447f95 -> org.sonar.plugins.core.timemachine.TimeMachineConfigurationPersister@442bf17b -> org.sonar.plugins.core.timemachine.NewCoverageFileAnalyzer@5d143a6b -> org.sonar.plugins.core.timemachine.NewItCoverageFileAnalyzer@5b07768a -> org.sonar.plugins.core.timemachine.NewOverallCoverageFileAnalyzer@46f78cb6 -> org.sonar.plugins.core.timemachine.NewCoverageAggregator@26372520 -> f(lines) -> f(generated_lines) -> f(ncloc) -> f(generated_ncloc) -> f(classes) -> f(packages) -> f(functions) -> f(accessors) -> f(statements) -> f(public_api) -> f(comment_lines) -> f(public_undocumented_api) -> f(commented_out_code_lines) -> f(complexity) -> f(complexity_in_classes) -> f(complexity_in_functions) -> f(class_complexity_distribution) -> f(function_complexity_distribution) -> f(file_complexity_distribution) -> f(lines_to_cover) -> f(uncovered_lines) -> f(conditions_to_cover) -> f(uncovered_conditions) -> f(it_lines_to_cover) -> f(it_uncovered_lines) -> f(it_conditions_to_cover) -> f(it_uncovered_conditions) -> f(overall_lines_to_cover) -> f(overall_uncovered_lines) -> f(overall_conditions_to_cover) -> f(overall_uncovered_conditions) -> f(rfc) -> f(rfc_distribution) -> f(lcom4_distribution) -> f(package_cycles) -> f(package_tangles) -> f(package_feedback_edges) -> f(package_edges_weight) -> f(new_lines_to_cover) -> f(new_uncovered_lines) -> f(new_conditions_to_cover) -> f(new_uncovered_conditions) -> f(new_it_lines_to_cover) -> f(new_it_uncovered_lines) -> f(new_it_conditions_to_cover) -> f(new_it_uncovered_conditions) -> f(new_overall_lines_to_cover) -> f(new_overall_uncovered_lines) -> f(new_overall_conditions_to_cover) -> f(new_overall_uncovered_conditions) -> org.sonar.batch.language.LanguageDistributionDecorator@4e4e4973 -> org.sonar.batch.debt.DebtDecorator@75b8452e -> org.sonar.batch.debt.NewDebtDecorator@14c60b63 -> DirectoryTangleIndexDecorator -> org.sonar.plugins.cpd.decorators.DuplicationDensityDecorator@39ec23c7 -> CountUnresolvedIssuesDecorator -> CountFalsePositivesDecorator -> CommentDensityDecorator -> f(file_complexity) -> f(class_complexity) -> f(function_complexity) -> org.sonar.plugins.core.sensors.CoverageDecorator@1ad9d22d -> org.sonar.plugins.core.sensors.LineCoverageDecorator@52759620 -> org.sonar.plugins.core.sensors.BranchCoverageDecorator@25d3392b -> org.sonar.plugins.core.sensors.ItLineCoverageDecorator@eaf2048 -> org.sonar.plugins.core.sensors.ItCoverageDecorator@b705e80 -> org.sonar.plugins.core.sensors.ItBranchCoverageDecorator@7e4c2b5d -> org.sonar.plugins.core.sensors.OverallLineCoverageDecorator@3ab32772 -> org.sonar.plugins.core.sensors.OverallCoverageDecorator@47e2cb79 -> org.sonar.plugins.core.sensors.OverallBranchCoverageDecorator@7a9c99cd -> org.sonar.batch.debt.SqaleRatingDecorator@56159b3c -> org.sonar.plugins.core.timemachine.TendencyDecorator@47130493 -> VariationDecorator
14:54:16.744 DEBUG - Decorator time:
    ManualMeasureDecorator: 217ms
    QProfileEventsDecorator: 13ms
    org.sonar.batch.design.ProjectDsmDecorator@12ebdf8b: 1ms
    org.sonar.batch.design.SubProjectDsmDecorator@3ba12861: 1ms
    org.sonar.batch.design.DirectoryDsmDecorator@516216dc: 17ms
    FileTangleIndexDecorator: 4ms
    SumDuplicationsDecorator: 26ms
    org.sonar.plugins.core.issue.IssueTrackingDecorator@7ecaef41: 93ms
    UnitTestDecorator: 0ms
    org.sonar.plugins.core.security.ApplyProjectRolesDecorator@1a099ee4: 3ms
    org.sonar.plugins.core.sensors.DirectoriesDecorator@59c4057d: 1ms
    org.sonar.plugins.core.sensors.FilesDecorator@54447f95: 2ms
    org.sonar.plugins.core.timemachine.TimeMachineConfigurationPersister@442bf17b: 18ms
    org.sonar.plugins.core.timemachine.NewCoverageFileAnalyzer@5d143a6b: 285ms
    org.sonar.plugins.core.timemachine.NewItCoverageFileAnalyzer@5b07768a: 3ms
    org.sonar.plugins.core.timemachine.NewOverallCoverageFileAnalyzer@46f78cb6: 7ms
    org.sonar.plugins.core.timemachine.NewCoverageAggregator@26372520: 2ms
    f(lines): 0ms
    f(generated_lines): 0ms
    f(ncloc): 1ms
    f(generated_ncloc): 1ms
    f(classes): 0ms
    f(packages): 0ms
    f(functions): 1ms
    f(accessors): 2ms
    f(statements): 1ms
    f(public_api): 0ms
    f(comment_lines): 0ms
    f(public_undocumented_api): 0ms
    f(commented_out_code_lines): 2ms
    f(complexity): 5ms
    f(complexity_in_classes): 0ms
    f(complexity_in_functions): 1ms
    f(class_complexity_distribution): 1ms
    f(function_complexity_distribution): 11ms
    f(file_complexity_distribution): 8ms
    f(lines_to_cover): 0ms
    f(uncovered_lines): 0ms
    f(conditions_to_cover): 2ms
    f(uncovered_conditions): 0ms
    f(it_lines_to_cover): 1ms
    f(it_uncovered_lines): 1ms
    f(it_conditions_to_cover): 0ms
    f(it_uncovered_conditions): 2ms
    f(overall_lines_to_cover): 0ms
    f(overall_uncovered_lines): 2ms
    f(overall_conditions_to_cover): 0ms
    f(overall_uncovered_conditions): 3ms
    f(rfc): 1ms
    f(rfc_distribution): 2ms
    f(lcom4_distribution): 2ms
    f(package_cycles): 1ms
    f(package_tangles): 1ms
    f(package_feedback_edges): 1ms
    f(package_edges_weight): 0ms
    f(new_lines_to_cover): 2ms
    f(new_uncovered_lines): 1ms
    f(new_conditions_to_cover): 3ms
    f(new_uncovered_conditions): 1ms
    f(new_it_lines_to_cover): 0ms
    f(new_it_uncovered_lines): 1ms
    f(new_it_conditions_to_cover): 1ms
    f(new_it_uncovered_conditions): 0ms
    f(new_overall_lines_to_cover): 1ms
    f(new_overall_uncovered_lines): 1ms
    f(new_overall_conditions_to_cover): 3ms
    f(new_overall_uncovered_conditions): 1ms
    org.sonar.batch.language.LanguageDistributionDecorator@4e4e4973: 5ms
    org.sonar.batch.debt.DebtDecorator@75b8452e: 71ms
    org.sonar.batch.debt.NewDebtDecorator@14c60b63: 14ms
    DirectoryTangleIndexDecorator: 1ms
    org.sonar.plugins.cpd.decorators.DuplicationDensityDecorator@39ec23c7: 4ms
    CountUnresolvedIssuesDecorator: 147ms
    CountFalsePositivesDecorator: 16ms
    CommentDensityDecorator: 7ms
    f(file_complexity): 12ms
    f(class_complexity): 2ms
    f(function_complexity): 2ms
    org.sonar.plugins.core.sensors.CoverageDecorator@1ad9d22d: 9ms
    org.sonar.plugins.core.sensors.LineCoverageDecorator@52759620: 8ms
    org.sonar.plugins.core.sensors.BranchCoverageDecorator@25d3392b: 6ms
    org.sonar.plugins.core.sensors.ItLineCoverageDecorator@eaf2048: 4ms
    org.sonar.plugins.core.sensors.ItCoverageDecorator@b705e80: 5ms
    org.sonar.plugins.core.sensors.ItBranchCoverageDecorator@7e4c2b5d: 6ms
    org.sonar.plugins.core.sensors.OverallLineCoverageDecorator@3ab32772: 3ms
    org.sonar.plugins.core.sensors.OverallCoverageDecorator@47e2cb79: 5ms
    org.sonar.plugins.core.sensors.OverallBranchCoverageDecorator@7a9c99cd: 4ms
    org.sonar.batch.debt.SqaleRatingDecorator@56159b3c: 32ms
    org.sonar.plugins.core.timemachine.TendencyDecorator@47130493: 81ms
    VariationDecorator: 67ms

14:54:16.744 INFO  - Store results in database
14:54:16.744 DEBUG - Execute org.sonar.batch.index.MeasurePersister
14:54:18.586 DEBUG - Updating semaphore batch-UIEMultiAccess_iOS
14:54:19.349 DEBUG - Execute org.sonar.batch.index.DuplicationPersister
14:54:19.349 DEBUG - Execute org.sonar.batch.index.SourcePersister
14:54:19.368 DEBUG - Processing Path/To/File
...
14:54:20.496 DEBUG - Execute org.sonar.batch.index.FileHashesPersister
14:54:20.514 DEBUG - Execute org.sonar.batch.issue.IssuePersister
14:54:20.516 DEBUG - Execute org.sonar.batch.phases.GraphPersister
14:54:20.528 DEBUG - Publish results
14:54:20.528 DEBUG - Download: http://localhost:Web/Server (no proxy)
14:54:20.548 INFO  - ANALYSIS SUCCESSFUL, you can browse http://localhost:Web/Server
14:54:20.548 INFO  - Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report.
14:54:20.549 DEBUG - Post-jobs : org.sonar.plugins.core.issue.notification.SendIssueNotificationsPostJob@1838650f
14:54:20.549 INFO  - Executing post-job class org.sonar.plugins.core.issue.notification.SendIssueNotificationsPostJob
14:54:20.550 DEBUG - Release semaphore on project : org.sonar.api.resources.Project@4d7f9397[id=853,key=Project,qualifier=TRK], with key batch-Project
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
Total time: 18.515s
Final Memory: 21M/1042M
INFO: ------------------------------------------------------------------------

**Comment by rompic** [comment]
This is not what i meant: Please click on quality profiles in the top menu and make a screenshot of the objective c section
![qprofile](https://cloud.githubusercontent.com/assets/6322123/6775112/917c5d24-d12c-11e4-8d8e-c2d80892a453.png)

**Comment by Yao0729** [comment]
You mean this one?
![screen shot 2015-03-23 at 12 03 44 am](https://cloud.githubusercontent.com/assets/10376484/6775572/37748112-d0f0-11e4-82db-70c13ca13eeb.png)

**Comment by zippy1978** [comment]
Hi,
I got it.

You must use 'OCLint' profile as default .

The other one 'Sonar Way' is a remain of the commercial plugin installation (you can remove it)

**Comment by Yao0729** [comment]
Yes. How can I set OCLint as default and remove Sonar Way?

Thanks so much!

**Comment by rompic** [comment]
Log in as administrator, click on "set as default" next to OCLint. click on delete next to Sonar Way

**Comment by Yao0729** [comment]
Thanks very much. It works now!

**Comment by SivaTrichy** [comment]
Hi @cyrilpicat 
I am using 
SonarQube 5.1.1
SonarRunner 2.4
Sonar Objective C plugin 0.4.0
I am getting the error Reporting 0 violations. I have set the OCLint profile as default. Kindly help.

Log:
INFO: SonarQube Server 5.1
16:35:24.797 INFO  - Load global repositories
16:35:24.985 INFO  - Load global repositories (done) | time=190ms
16:35:24.987 INFO  - Server id: 20150610120629
16:35:24.989 INFO  - User cache: /Users/.../.sonar/cache
16:35:24.997 INFO  - Install plugins
16:35:25.292 INFO  - Install JDBC driver
16:35:25.298 INFO  - Create JDBC datasource for jdbc:mysql://localhost:3306/sonar?useUnicode=true&amp;characterEncoding=utf8
16:35:26.686 INFO  - Initializing Hibernate
16:35:28.199 ERROR - No license for plugin report
16:35:28.480 INFO  - Load project repositories
16:35:28.655 INFO  - Load project repositories (done) | time=175ms
16:35:28.655 INFO  - Load project settings
16:35:28.990 INFO  - Load technical debt model
16:35:29.020 INFO  - Apply project exclusions
16:35:29.499 INFO  - -------------  Scan Sonar Local 1
16:35:29.507 INFO  - Load module settings
16:35:29.686 INFO  - Language is forced to objc
16:35:29.697 INFO  - Load rules
16:35:29.942 INFO  - Base dir: /Users/.../Tryouts/SphereButtons
16:35:29.943 INFO  - Working dir: /Users/.../Tryouts/SphereButtons/.sonar
16:35:29.943 INFO  - Source paths: .
16:35:29.944 INFO  - Source encoding: UTF-8, default locale: en_US
16:35:29.944 INFO  - Index files
16:35:29.985 INFO  - 11 files indexed
16:35:30.137 INFO  - Quality profile for objc: Test
16:35:30.177 INFO  - Trying to guess scm provider from project layout...
16:35:30.177 INFO  - Found SCM type: git
16:35:30.186 INFO  - Sensor Lines Sensor
16:35:30.206 INFO  - Sensor Lines Sensor (done) | time=20ms
16:35:30.206 INFO  - Sensor QProfileSensor
16:35:30.211 INFO  - Sensor QProfileSensor (done) | time=5ms
16:35:30.211 INFO  - Sensor InitialOpenIssuesSensor
16:35:30.221 INFO  - Sensor InitialOpenIssuesSensor (done) | time=10ms
16:35:30.222 INFO  - Sensor ProjectLinksSensor
16:35:30.232 INFO  - Sensor ProjectLinksSensor (done) | time=10ms
16:35:30.232 INFO  - Sensor VersionEventsSensor
16:35:30.252 INFO  - Sensor VersionEventsSensor (done) | time=20ms
16:35:30.252 INFO  - Sensor ScmStatsSensor
16:35:30.253 INFO  - Collection SCM Change log for the last 0 days
16:35:30.280 INFO  - Executing: /bin/sh -c cd /Users/.../Tryouts/SphereButtons && git whatchanged '--until=2015-06-10 11:05:30 +0000' --date=iso -- /Users/.../Tryouts/SphereButtons
16:35:30.280 INFO  - Working directory: /Users/.../Tryouts/SphereButtons
16:35:30.671 INFO  - Sensor ScmStatsSensor (done) | time=419ms
16:35:30.671 INFO  - Sensor ObjectiveCSquidSensor
16:35:30.818 INFO  - Sensor ObjectiveCSquidSensor (done) | time=147ms
16:35:30.818 INFO  - Sensor Objective-C SurefireSensor
16:35:30.818 INFO  - parsing sonar-reports
16:35:30.883 INFO  - Sensor Objective-C SurefireSensor (done) | time=65ms
16:35:30.883 INFO  - Sensor org.sonar.plugins.objectivec.coverage.CoberturaSensor@7ff2ad88
16:35:30.893 INFO  - Processing coverage report /Users/.../Tryouts/SphereButtons/sonar-reports/coverage.xml
16:35:30.894 INFO  - Sensor org.sonar.plugins.objectivec.coverage.CoberturaSensor@7ff2ad88 (done) | time=11ms
16:35:30.894 INFO  - Sensor org.sonar.plugins.objectivec.violations.OCLintSensor@4e68c590
16:35:30.894 INFO  - Processing OCLint report /Users/.../Tryouts/SphereButtons/sonar-reports/oclint.xml
16:35:30.896 ERROR - Reporting 0 violations.
16:35:30.896 INFO  - Sensor org.sonar.plugins.objectivec.violations.OCLintSensor@4e68c590 (done) | time=2ms
16:35:30.896 INFO  - Sensor SCM Sensor
16:35:30.896 INFO  - SCM Sensor is disabled
16:35:30.896 INFO  - Sensor SCM Sensor (done) | time=0ms
16:35:30.896 INFO  - Sensor CPD Sensor
16:35:30.896 INFO  - DefaultCpdEngine is used for objc
16:35:30.897 INFO  - Cross-project analysis disabled
16:35:30.970 INFO  - Sensor CPD Sensor (done) | time=74ms
16:35:30.972 INFO  - No quality gate is configured.
16:35:31.021 INFO  - Compare to previous analysis (2015-06-10)
16:35:31.029 INFO  - Compare over 30 days (2015-05-11, analysis of Wed May 27 13:43:23 IST 2015)
16:35:31.261 INFO  - Execute decorators...
16:35:31.577 INFO  - Store results in database
16:35:32.099 INFO  - Analysis reports generated in 17ms, dir size=1 KB
16:35:32.114 INFO  - Analysis reports compressed in 14ms, zip size=4 KB
16:35:32.198 INFO  - Analysis reports sent to server in 84ms
16:35:32.198 INFO  - ANALYSIS SUCCESSFUL, you can browse http://localhost:9000/dashboard/index/sonar-local-1
16:35:32.199 INFO  - Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report.
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
Total time: 8.265s
Final Memory: 14M/179M
INFO: ------------------------------------------------------------------------
- returnValue=0
- set +x

Dashboard: I am getting LOC and duplication details but not the issues, as the code has violating snippets.

![screen shot 2015-06-10 at 4 43 40 pm](https://cloud.githubusercontent.com/assets/12826357/8081169/4f79506a-0f90-11e5-9047-fb68748a9832.png)

**Comment by jinkerry** [comment]
same problem  like SivaTrichy

**Comment by wdvr** [comment]
Same here

**Comment by Lrdcq** [comment]
Same here and using: SonarQube 5.5 , sonar-objective-c-plugin-0.5.0-SNAPSHOT.jar.
No error in processing OCLint report at all. Like this:

> WARN: sonar-runner script is deprecated. Please use sonar-scanner instead.
> INFO: Scanner configuration file: /Users/xx/Downloads/sonar-scanner-2.6.1/conf/sonar-scanner.properties
> INFO: Project root configuration file: /Users/xx/sk/ios/Shopkeeper/sonar-project.properties
> INFO: SonarQube Scanner 2.6.1
> INFO: Java 1.7.0_79 Oracle Corporation (64-bit)
> INFO: Mac OS X 10.11.3 x86_64
> INFO: Error stacktraces are turned on.
> INFO: User cache: /Users/xx/.sonar/cache
> INFO: Load global repositories
> INFO: Load global repositories (done) | time=244ms
> WARN: Property 'sonar.jdbc.url' is not supported any more. It will be ignored. There is no longer any DB connection to the SQ database.
> INFO: User cache: /Users/xx/.sonar/cache
> INFO: Load plugins index
> INFO: Load plugins index (done) | time=28ms
> INFO: SonarQube server 5.5
> INFO: Default locale: "zh_CN", source code encoding: "UTF-8"
> INFO: Process project properties
> INFO: Load project repositories
> INFO: Load project repositories (done) | time=455ms
> INFO: Load quality profiles
> INFO: Load quality profiles (done) | time=251ms
> INFO: Load active rules
> INFO: Load active rules (done) | time=1021ms
> INFO: Publish mode
> INFO: -------------  Scan xgfe.shopkeeper.app.ios
> INFO: Load server rules
> INFO: Load server rules (done) | time=127ms
> INFO: Base dir: /Users/xx/sk/ios/Shopkeeper
> INFO: Working dir: /Users/xx/sk/ios/Shopkeeper/.sonar
> INFO: Source paths: Shopkeeper
> INFO: Source encoding: UTF-8, default locale: zh_CN
> INFO: Index files
> INFO: 298 files indexed
> INFO: Quality profile for objectivec: OCLint
> INFO: JaCoCoSensor: JaCoCo report not found : /Users/xx/sk/ios/Shopkeeper/target/jacoco.exec
> INFO: JaCoCoItSensor: JaCoCo IT report not found: /Users/xx/sk/ios/Shopkeeper/target/jacoco-it.exec
> INFO: Sensor Lines Sensor
> INFO: Sensor Lines Sensor (done) | time=285ms
> INFO: Sensor Objective-C Squid Sensor
> INFO: Sensor Objective-C Squid Sensor (done) | time=1987ms
> INFO: Sensor Objective-C OCLint Sensor
> **INFO: parsing /Users/xx/sk/ios/Shopkeeper/oclint.xml**
> INFO: Sensor Objective-C OCLint Sensor (done) | time=127ms
> INFO: Sensor SCM Sensor
> INFO: Sensor SCM Sensor (done) | time=3ms
> INFO: Sensor Zero Coverage Sensor
> INFO: Sensor Zero Coverage Sensor (done) | time=269ms
> INFO: Sensor Code Colorizer Sensor
> INFO: Sensor Code Colorizer Sensor (done) | time=13ms
> INFO: Sensor CPD Block Indexer
> INFO: DefaultCpdBlockIndexer is used for objectivec
> INFO: Sensor CPD Block Indexer (done) | time=618ms
> INFO: Calculating CPD for 195 files
> INFO: CPD calculation finished
> INFO: Analysis report generated in 802ms, dir size=898 KB
> INFO: Analysis reports compressed in 703ms, zip size=539 KB
> INFO: Analysis report uploaded in 603ms
> INFO: ANALYSIS SUCCESSFUL, you can browse http://10.xx.xx.177:8080/dashboard/index/com.xx.xx.shopkeeper.ep
> INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
> INFO: More about the report processing at http://10.xx.xx:8080/api/ce/task?id=AVUKCdziwKC4N1IQyl3C
> INFO: ------------------------------------------------------------------------
> INFO: EXECUTION SUCCESS
> INFO: ------------------------------------------------------------------------
> INFO: Total time: 14.109s
> INFO: Final Memory: 41M/144M
> INFO: ------------------------------------------------------------------------
