### ISSUE TITLE
SonarQube 5.0 incompatibility

### ISSUE THREAD

**Issue by aheritier** [octo-technology/sonar-objective-c#75]
Hi,

  I upgraded my instance to sonarqube 5.0 and the plugin fails with this error : https://gist.github.com/aheritier/6f0d9c4cd6aa7dcc4be0

**Comment by zippy1978** [comment]
Hi,
I fixed the Sonar 5.0 support.

Here is the PR : https://github.com/octo-technology/sonar-objective-c/pull/76

**Comment by aheritier** [comment]
Cool, thanks. I will test it ASAP

**Comment by aheritier** [comment]
https://ci.exoplatform.org/job/mobile-ios-develop-sonar/105/console
https://sonar.exoplatform.org/dashboard/index/231502
Yeah. It works. Thx a lot

**Comment by cyrilpicat** [comment]
cool, thanks!
