### ISSUE TITLE
Support for swift

### ISSUE THREAD

**Issue by rompic** [octo-technology/sonar-objective-c#93]
How hard would It be to Support https://github.com/realm/SwiftLint

**Comment by rompic** [comment]
they now support custom reporters. maybe we could harness those?
https://github.com/realm/SwiftLint/issues/42

**Comment by rompic** [comment]
https://github.com/realm/SwiftLint/issues/175

**Comment by cyrilpicat** [comment]
thanks for the info, keep us tuned.

Cyril

**Comment by rompic** [comment]
https://github.com/Backelite/sonar-swift

**Comment by zippy1978** [comment]
Hi, 

I just released a first version of the Swift SonarQube plugin here : https://github.com/Backelite/sonar-swift
